development: &default
  adapter: postgresql
  encoding: unicode
  database: bakery_development
  pool: 5
  username: rails
  password: password
  host: localhost #db

test:
  <<: *default
  database: bakery_test

production:
  <<: *default
  database: bakery