# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 592cc88ad257805eec9f9a11bafd233d4393bf3ea704ce368c9f5c50765c3264d5d70a0186f4a12f03d3aea3a3febb8027b18d1f077b9b9f1d54a856331b700f

test:
  secret_key_base: 4c429b752591286dfc17f661616fe64672eb2b653561d2a1d3dd7c68a10dd430b64dc4576c756265b231c673022ed91be0e13fc2d132968fc4adca630fd18386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
